# Generated by Django 3.0.4 on 2020-03-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia', '0004_on_delete_arg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
