# Generated by Django 4.1.10 on 2023-10-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zinnia", "0005_category_mptt_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="related",
            field=models.ManyToManyField(
                blank=True, to="zinnia.entry", verbose_name="related entries"
            ),
        ),
    ]
