# Generated by Django 4.1.2 on 2022-10-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia', '0005_category_mptt_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='related',
            field=models.ManyToManyField(blank=True, to='zinnia.entry', verbose_name='related entries'),
        ),
    ]
